package mago.apps.hertz.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0B47F6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001257)
val md_theme_light_secondary = Color(0xFF006688)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC2E8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2B)
val md_theme_light_tertiary = Color(0xFFBA0C52)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DF)
val md_theme_light_onTertiaryContainer = Color(0xFF3F0017)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF001E2F)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF001E2F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFE6F2FF)
val md_theme_light_inverseSurface = Color(0xFF00344E)
val md_theme_light_inversePrimary = Color(0xFFB9C3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0B47F6)
val md_theme_light_surfaceTintColor = Color(0xFF0B47F6)

val md_theme_dark_primary = Color(0xFFB9C3FF)
val md_theme_dark_onPrimary = Color(0xFF00228A)
val md_theme_dark_primaryContainer = Color(0xFF0034C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_secondary = Color(0xFF76D1FF)
val md_theme_dark_onSecondary = Color(0xFF003548)
val md_theme_dark_secondaryContainer = Color(0xFF004D67)
val md_theme_dark_onSecondaryContainer = Color(0xFFC2E8FF)
val md_theme_dark_tertiary = Color(0xFFFFB1C0)
val md_theme_dark_onTertiary = Color(0xFF660029)
val md_theme_dark_tertiaryContainer = Color(0xFF90003D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001E2F)
val md_theme_dark_onBackground = Color(0xFFC9E6FF)
val md_theme_dark_surface = Color(0xFF001E2F)
val md_theme_dark_onSurface = Color(0xFFC9E6FF)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF001E2F)
val md_theme_dark_inverseSurface = Color(0xFFC9E6FF)
val md_theme_dark_inversePrimary = Color(0xFF0B47F6)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB9C3FF)
val md_theme_dark_surfaceTintColor = Color(0xFFB9C3FF)


val seed = Color(0xFF2152FF)
